import type { RawToolEntry } from '@/lib/tools-registry-data/types';
import { categoryOrThrow } from '@/lib/tools-registry-data/categories';

export const pdfEntries: RawToolEntry[] = [
  {
    id: 'merge-pdf',
    path: '/pdf-tools/merge/merge-pdf',
    title: 'ادغام PDF - جعبه ابزار فارسی',
    description: 'ادغام چند فایل PDF در یک فایل واحد',
    keywords: [
      'ادغام PDF',
      'ترکیب PDF',
      'ادغام فایل پی دی اف',
      'merge pdf',
      'چسباندن صفحات PDF',
      'ادغام چند PDF',
      'یکپارچه سازی PDF',
    ],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'چند فایل PDF را به یک فایل واحد و منظم تبدیل کنید.',
      steps: [
        'فایل‌های PDF را انتخاب کنید.',
        'ترتیب فایل‌ها را بررسی کنید.',
        'گزینه ادغام را بزنید و فایل خروجی را دانلود کنید.',
      ],
      tips: ['حداقل دو فایل برای ادغام لازم است.', 'فایل خروجی را پیش از اشتراک بررسی کنید.'],
      faq: [
        {
          question: 'آیا محدودیت تعداد فایل وجود دارد؟',
          answer: 'خیر، اما تعداد زیاد فایل ممکن است زمان پردازش را افزایش دهد.',
        },
        {
          question: 'آیا فایل‌ها روی سرور ذخیره می‌شوند؟',
          answer: 'خیر، همه چیز در مرورگر انجام می‌شود.',
        },
      ],
    },
  },
  {
    id: 'split-pdf',
    path: '/pdf-tools/split/split-pdf',
    title: 'تقسیم PDF - جعبه ابزار فارسی',
    description: 'تقسیم فایل‌های PDF به چند فایل کوچک‌تر',
    keywords: [
      'تقسیم PDF',
      'جدا کردن صفحات PDF',
      'split pdf',
      'بریدن فایل PDF',
      'خروجی چند فایل PDF',
      'تفکیک صفحات PDF',
    ],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'صفحات مورد نیاز را جدا کنید و فایل‌های کوچک‌تر بسازید.',
      steps: [
        'فایل PDF را انتخاب کنید.',
        'بازه صفحات مورد نظر را وارد کنید.',
        'عملیات تقسیم را اجرا و فایل‌ها را دانلود کنید.',
      ],
      faq: [
        {
          question: 'فرمت بازه صفحات چیست؟',
          answer: 'مثلاً 1-3,5,7-9 برای انتخاب صفحات.',
        },
      ],
    },
  },
  {
    id: 'compress-pdf',
    path: '/pdf-tools/compress/compress-pdf',
    title: 'فشرده‌سازی PDF - جعبه ابزار فارسی',
    description: 'کاهش حجم فایل‌های PDF با حفظ کیفیت',
    keywords: [
      'فشرده سازی PDF',
      'کاهش حجم PDF',
      'compress pdf',
      'کم کردن حجم فایل PDF',
      'بهینه سازی PDF',
      'کاهش حجم پی دی اف',
    ],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'حجم فایل PDF را کاهش دهید تا ارسال و اشتراک آسان‌تر شود.',
      steps: [
        'فایل PDF را انتخاب کنید.',
        'سطح فشرده‌سازی را مشخص کنید.',
        'فایل فشرده‌شده را دانلود کنید.',
      ],
      tips: ['سطح فشرده‌سازی بالاتر ممکن است کیفیت را کاهش دهد.'],
      faq: [
        {
          question: 'آیا متن‌ها خوانا می‌مانند؟',
          answer: 'بله، فشرده‌سازی با حفظ خوانایی متن انجام می‌شود.',
        },
      ],
    },
  },
  {
    id: 'pdf-to-image',
    path: '/pdf-tools/convert/pdf-to-image',
    title: 'تبدیل PDF به تصویر - جعبه ابزار فارسی',
    description: 'تبدیل صفحات PDF به تصاویر با کیفیت مناسب',
    keywords: [
      'تبدیل PDF به عکس',
      'PDF به تصویر',
      'pdf to image',
      'خروجی JPG از PDF',
      'خروجی PNG از PDF',
      'تبدیل پی دی اف به عکس',
    ],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'هر صفحه PDF را به تصویر جداگانه تبدیل کنید.',
      steps: [
        'فایل PDF را انتخاب کنید.',
        'فرمت خروجی تصویر را انتخاب کنید.',
        'تصاویر خروجی را دانلود کنید.',
      ],
      faq: [
        {
          question: 'خروجی چه فرمتی دارد؟',
          answer: 'فرمت‌های رایج مثل PNG یا JPG بسته به انتخاب شما.',
        },
      ],
    },
  },
  {
    id: 'image-to-pdf',
    path: '/pdf-tools/convert/image-to-pdf',
    title: 'تبدیل تصویر به PDF - جعبه ابزار فارسی',
    description: 'تبدیل تصاویر به فایل PDF مرتب و قابل چاپ',
    keywords: [
      'تبدیل عکس به PDF',
      'تصویر به PDF',
      'image to pdf',
      'تبدیل jpg به pdf',
      'تبدیل png به pdf',
      'ساخت PDF از عکس',
    ],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'چند تصویر را به یک فایل PDF واحد تبدیل کنید.',
      steps: [
        'تصاویر را انتخاب کنید.',
        'ترتیب تصاویر را مشخص کنید.',
        'فایل PDF خروجی را دانلود کنید.',
      ],
      faq: [
        {
          question: 'آیا می‌توان چند تصویر را همزمان انتخاب کرد؟',
          answer: 'بله، امکان انتخاب چند تصویر وجود دارد.',
        },
      ],
    },
  },
  {
    id: 'decrypt-pdf',
    path: '/pdf-tools/security/decrypt-pdf',
    title: 'حذف رمز PDF - جعبه ابزار فارسی',
    description: 'باز کردن قفل فایل‌های PDF با رمز معتبر',
    keywords: [
      'حذف رمز PDF',
      'باز کردن قفل PDF',
      'decrypt pdf',
      'برداشتن پسورد PDF',
      'حذف پسورد پی دی اف',
    ],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'با وارد کردن رمز صحیح، محدودیت فایل PDF را بردارید.',
      steps: [
        'فایل PDF رمزدار را انتخاب کنید.',
        'رمز فایل را وارد کنید.',
        'فایل بدون رمز را دانلود کنید.',
      ],
      faq: [
        {
          question: 'آیا بدون رمز می‌توان فایل را باز کرد؟',
          answer: 'خیر، برای حذف رمز، داشتن رمز صحیح ضروری است.',
        },
      ],
    },
  },
  {
    id: 'encrypt-pdf',
    path: '/pdf-tools/security/encrypt-pdf',
    title: 'رمزگذاری PDF - جعبه ابزار فارسی',
    description: 'افزودن رمز عبور به فایل‌های PDF برای امنیت بیشتر',
    keywords: [
      'رمزگذاری PDF',
      'گذاشتن پسورد PDF',
      'encrypt pdf',
      'قفل کردن PDF',
      'رمز گذاشتن پی دی اف',
    ],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'برای محافظت از فایل‌های PDF رمزگذاری انجام دهید.',
      steps: [
        'فایل PDF را انتخاب کنید.',
        'رمز عبور را تنظیم کنید.',
        'فایل رمزگذاری‌شده را دانلود کنید.',
      ],
      faq: [
        {
          question: 'آیا رمز را ذخیره می‌کنید؟',
          answer: 'خیر، رمز عبور فقط برای پردازش محلی استفاده می‌شود.',
        },
      ],
    },
  },
  {
    id: 'watermark-pdf',
    path: '/pdf-tools/watermark/add-watermark',
    title: 'واترمارک PDF - جعبه ابزار فارسی',
    description: 'افزودن واترمارک متنی یا تصویری به فایل‌های PDF',
    keywords: [
      'واترمارک PDF',
      'watermark pdf',
      'اضافه کردن واترمارک',
      'متن واترمارک PDF',
      'لوگو روی PDF',
    ],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'با افزودن واترمارک، مالکیت یا برند خود را روی PDF ثبت کنید.',
      steps: [
        'فایل PDF را انتخاب کنید.',
        'متن یا تصویر واترمارک را وارد کنید.',
        'فایل واترمارک‌شده را دانلود کنید.',
      ],
      faq: [
        {
          question: 'آیا می‌توان شفافیت واترمارک را تنظیم کرد؟',
          answer: 'بله، میزان شفافیت قابل تنظیم است.',
        },
      ],
    },
  },
  {
    id: 'rotate-pdf',
    path: '/pdf-tools/edit/rotate-pages',
    title: 'چرخش صفحات PDF - جعبه ابزار فارسی',
    description: 'چرخاندن صفحات PDF برای اصلاح جهت نمایش',
    keywords: ['چرخش صفحات PDF', 'rotate pdf', 'اصلاح جهت PDF', 'چرخاندن صفحه پی دی اف'],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'صفحات PDF را در جهت درست بچرخانید و ذخیره کنید.',
      steps: [
        'فایل PDF را انتخاب کنید.',
        'صفحات مورد نظر و زاویه چرخش را مشخص کنید.',
        'فایل اصلاح‌شده را دانلود کنید.',
      ],
    },
  },
  {
    id: 'reorder-pdf',
    path: '/pdf-tools/edit/reorder-pages',
    title: 'جابجایی صفحات PDF - جعبه ابزار فارسی',
    description: 'مرتب‌سازی و جابجایی صفحات PDF',
    keywords: ['جابجایی صفحات PDF', 'مرتب کردن صفحات PDF', 'reorder pdf', 'تغییر ترتیب PDF'],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'صفحات PDF را با ترتیب دلخواه بچینید.',
      steps: [
        'فایل PDF را انتخاب کنید.',
        'صفحات را با ترتیب جدید مرتب کنید.',
        'فایل مرتب‌شده را دانلود کنید.',
      ],
    },
  },
  {
    id: 'delete-pdf-pages',
    path: '/pdf-tools/edit/delete-pages',
    title: 'حذف صفحات PDF - جعبه ابزار فارسی',
    description: 'حذف صفحات اضافی از فایل PDF',
    keywords: ['حذف صفحات PDF', 'delete pdf pages', 'برداشتن صفحه از PDF', 'حذف صفحه پی دی اف'],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'صفحات غیرضروری را حذف کنید و فایل بهینه بسازید.',
      steps: [
        'فایل PDF را انتخاب کنید.',
        'بازه صفحات قابل حذف را وارد کنید.',
        'فایل نهایی را دانلود کنید.',
      ],
    },
  },
  {
    id: 'extract-pdf-pages',
    path: '/pdf-tools/extract/extract-pages',
    title: 'استخراج صفحات PDF - جعبه ابزار فارسی',
    description: 'استخراج چند صفحه از PDF و ایجاد فایل جدید',
    keywords: [
      'استخراج صفحات PDF',
      'extract pdf pages',
      'جدا کردن صفحات PDF',
      'خارج کردن صفحه از PDF',
    ],
    indexable: true,
    lastModified: '2026-02-04',
    kind: 'tool',
    category: categoryOrThrow('pdf'),
    content: {
      intro: 'تنها صفحات مورد نیاز را جدا کرده و به فایل جدید تبدیل کنید.',
      steps: [
        'فایل PDF را انتخاب کنید.',
        'بازه صفحات مورد نظر را وارد کنید.',
        'فایل استخراج‌شده را دانلود کنید.',
      ],
    },
  },
];
